name: Music  That Matters
favicon: null
layout_spectrum: 0.93923
typography_spectrum: 0.91516
title: Music with Intentional Meaning
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b3d0ec'
    - '#63a2b9'
    - '#244069'
    - '#30717e'
    - '#85383a'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
