name: Music  That Matters
favicon: null
layout_spectrum: 0.45909
typography_spectrum: 0.91516
title: Music with Intentional Meaning
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#000000'
    - '#464d76'
    - '#1b1f2f'
    - '#ac7e83'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
